"""empty message

Revision ID: 72970c1cfb25
Revises: d6238a98867c
Create Date: 2020-08-09 10:38:47.267506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72970c1cfb25'
down_revision = 'd6238a98867c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('ingredients', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'ingredients')
    # ### end Alembic commands ###
